### ISSUE TITLE
repo_cleaner并入lilac

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/misc_scripts#13]
如题，主要是为了干掉package.list，既然lilac已经load mod了，就一并干了这事得了。

另外lilac.py中的packages参数和package.list含义重叠，可以合并成一个

**Comment by lilydjwg** [comment]
lilac.py 没有 packages 参数啊。
不并入的原因是，这俩东西是相对独立的，之间没有依赖关系。而且 repocleaner 要求 root 权限，而 lilac 只是普通维护者权限。

**Comment by petronny** [comment]
> lilac.py 没有 packages 参数啊。

我记得原来是有的。原来的作用是如果多个pkgname，只打包列出的，默认是None，表示所有的都打包。

> repocleaner 要求 root 权限

竟然要求root权限，不科学啊，能改一改build机的配置取消这个root权限么？

**Comment by lilydjwg** [comment]
哦，那个用于减少重复工作的。后来因为 makepkg 不再支持只打部分包而删掉了。

repocleaner 要能够删除所有打包者的包，当然 root 权限比较方便啦。

**Comment by petronny** [comment]
我也是查文档才找到这个的。

> repocleaner 要能够删除所有打包者的包，当然 root 权限比较方便啦。

应该是从/home/repo挪过去的包吧，能挪过去的时候顺便改个权限么？

**Comment by lilydjwg** [comment]
> 应该是从/home/repo挪过去的包吧，能挪过去的时候顺便改个权限么？

然后你就会发现包打错了，挪错了，但没有权限修复问题了。

**Comment by petronny** [comment]
等一下没有跟上😂
我目前的理解是，大家把自己打的包放/home/repo，然后某定时脚本把这里的挪到真正的repo里。
如果打包出错了应该是再打包一个bump了pkgrel的放/home/repo，应该没问题吧？
挪错了又是啥情况。。。

**Comment by lilydjwg** [comment]
也是可以紧急降级包（touch 旧版本）或者删除包的。再打新包可能会花很长的时间，期间坏包会扩散。把本来不打算放进源的包误放进去了的话，如果不能直接删除，就要等一天了。

目前的设定是，往里边放的包都保留原本的权限，这样包放进去之后打包者还有能力去变更。

其实在 lilac 之前的时代，所有者信息代表了包的维护者的。只是后来没用上这个设定就有了 lilac。

**Comment by petronny** [comment]
那删包改成touch一个 旧包.rm 文件，扫描到了就去repo删除呢？

**Comment by lilydjwg** [comment]
多麻烦啊。

为什么要合并呢？除了部署方便点，合并还有啥好处？

**Comment by petronny** [comment]
干掉package.list啊，配置文件统一到一处

**Comment by lilydjwg** [comment]
这个让 repocleaner 支持 lilac.yaml 就可以啦。

**Comment by petronny** [comment]
然后我肯定会搞lilac.py兼容😂
然后就回到这里了。。。

所以主要还是部署方便吧。。。

**Comment by holymonson** [comment]
https://github.com/archlinuxcn/lilac/pull/142#issuecomment-607669190

原来以前已经讨论过了。。
不需要整个并入，repocleaner import lilac的函数就可以啦，运行是看执行者权限的，不是由root执行lilac的主程序的话，没有安全问题吧。。
